import { boolean, date, datetime, decimal, int, mysqlTable, text, timestamp, varchar } from 'drizzle-orm/mysql-core'

const id = () => int('id').autoincrement().primaryKey()

export const user = mysqlTable('user', { id: varchar('id', { length: 191 }).primaryKey(), name: varchar('name', { length: 191 }).notNull(), email: varchar('email', { length: 191 }).notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), role: varchar('role', { length: 32 }).notNull().default('admin'), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()) })
export const session = mysqlTable('session', { id: varchar('id', { length: 191 }).primaryKey(), expiresAt: datetime('expiresAt').notNull(), token: varchar('token', { length: 191 }).notNull().unique(), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()), ipAddress: varchar('ipAddress', { length: 191 }), userAgent: text('userAgent'), userId: varchar('userId', { length: 191 }).notNull() })
export const account = mysqlTable('account', { id: varchar('id', { length: 191 }).primaryKey(), accountId: varchar('accountId', { length: 191 }).notNull(), providerId: varchar('providerId', { length: 191 }).notNull(), userId: varchar('userId', { length: 191 }).notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: datetime('accessTokenExpiresAt'), refreshTokenExpiresAt: datetime('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()) })
export const verification = mysqlTable('verification', { id: varchar('id', { length: 191 }).primaryKey(), identifier: varchar('identifier', { length: 191 }).notNull(), value: text('value').notNull(), expiresAt: datetime('expiresAt').notNull(), createdAt: datetime('createdAt').default(new Date()), updatedAt: datetime('updatedAt').default(new Date()) })

export const trucks = mysqlTable('truck', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), code: varchar('code', { length: 64 }).notNull(), plate: varchar('plate', { length: 32 }).notNull(), brand: varchar('brand', { length: 100 }).notNull(), model: varchar('model', { length: 100 }).notNull(), year: int('year'), capacityTons: decimal('capacity_tons', { precision: 10, scale: 2 }), fuelType: varchar('fuel_type', { length: 32 }).default('Diesel'), benchmarkKmL: decimal('benchmark_km_l', { precision: 10, scale: 2 }), currentKm: decimal('current_km', { precision: 12, scale: 2 }).notNull().default('0'), status: varchar('status', { length: 32 }).notNull().default('active'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const drivers = mysqlTable('driver', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), userId: varchar('user_id', { length: 191 }), name: varchar('name', { length: 191 }).notNull(), email: varchar('email', { length: 191 }), phone: varchar('phone', { length: 64 }), employeeId: varchar('employee_id', { length: 64 }), assignedTruckId: int('assigned_truck_id'), status: varchar('status', { length: 32 }).notNull().default('active'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const transportOperation = mysqlTable('transport_operation', { id: id(), userId: varchar('user_id', { length: 191 }).notNull(), truckId: int('truck_id'), driverId: int('driver_id'), operationDate: date('operation_date').notNull(), truckCode: varchar('truck_code', { length: 64 }).notNull(), driverName: varchar('driver_name', { length: 191 }).notNull(), city: varchar('city', { length: 191 }).notNull(), km: decimal('km', { precision: 12, scale: 2 }).notNull(), tons: decimal('tons', { precision: 12, scale: 2 }).notNull(), liters: decimal('liters', { precision: 12, scale: 2 }).notNull(), trips: decimal('trips', { precision: 10, scale: 2 }).notNull().default('1'), status: varchar('status', { length: 32 }).notNull().default('concluida'), notes: text('notes'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const fuelRecord = mysqlTable('fuel_record', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), driverId: int('driver_id'), recordDate: date('record_date').notNull(), odometer: decimal('odometer', { precision: 12, scale: 2 }), km: decimal('km', { precision: 12, scale: 2 }).notNull(), liters: decimal('liters', { precision: 12, scale: 2 }).notNull(), pricePerLiter: decimal('price_per_liter', { precision: 10, scale: 3 }).notNull().default('0'), totalCost: decimal('total_cost', { precision: 12, scale: 2 }).notNull().default('0'), station: varchar('station', { length: 191 }), fuelType: varchar('fuel_type', { length: 32 }).notNull().default('Diesel'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const maintenanceRecord = mysqlTable('maintenance_record', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id').notNull(), maintenanceDate: date('maintenance_date').notNull(), maintenanceType: varchar('maintenance_type', { length: 32 }).notNull().default('corretiva'), problem: varchar('problem', { length: 191 }).notNull(), description: text('description'), partsCost: decimal('parts_cost', { precision: 12, scale: 2 }).notNull().default('0'), laborCost: decimal('labor_cost', { precision: 12, scale: 2 }).notNull().default('0'), status: varchar('status', { length: 32 }).notNull().default('aberta'), resolvedAt: date('resolved_at'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const downtimeRecord = mysqlTable('downtime_record', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id').notNull(), startedAt: date('started_at').notNull(), endedAt: date('ended_at'), reason: varchar('reason', { length: 191 }).notNull(), potentialRevenue: decimal('potential_revenue', { precision: 12, scale: 2 }).notNull().default('0'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const revenue = mysqlTable('revenue', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), operationId: int('operation_id'), revenueDate: date('revenue_date').notNull(), description: varchar('description', { length: 191 }).notNull(), amount: decimal('amount', { precision: 12, scale: 2 }).notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const expense = mysqlTable('expense', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), expenseDate: date('expense_date').notNull(), category: varchar('category', { length: 100 }).notNull(), description: varchar('description', { length: 191 }).notNull(), amount: decimal('amount', { precision: 12, scale: 2 }).notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const monthlyClosure = mysqlTable('monthly_closure', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), referenceMonth: date('reference_month').notNull(), status: varchar('status', { length: 32 }).notNull().default('open'), closedAt: datetime('closed_at'), closedBy: varchar('closed_by', { length: 191 }), createdAt: datetime('created_at').notNull().default(new Date()) })
export const incident = mysqlTable('incident', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), driverId: int('driver_id'), incidentDate: date('incident_date').notNull(), category: varchar('category', { length: 100 }).notNull(), description: text('description').notNull(), status: varchar('status', { length: 32 }).notNull().default('aberta'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const benchmark = mysqlTable('benchmark', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), metric: varchar('metric', { length: 100 }).notNull(), targetValue: decimal('target_value', { precision: 12, scale: 2 }).notNull(), validFrom: date('valid_from').notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const notification = mysqlTable('notification', { id: id(), userId: varchar('user_id', { length: 191 }).notNull(), title: varchar('title', { length: 191 }).notNull(), message: text('message').notNull(), readAt: datetime('read_at'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const setting = mysqlTable('setting', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), settingKey: varchar('setting_key', { length: 100 }).notNull(), settingValue: text('setting_value').notNull(), updatedAt: datetime('updated_at').notNull().default(new Date()) })
export const preventiveMaintenanceRule = mysqlTable('preventive_maintenance_rule', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), truckId: int('truck_id'), name: varchar('name', { length: 191 }).notNull(), component: varchar('component', { length: 100 }).notNull(), intervalKm: decimal('interval_km', { precision: 12, scale: 2 }), intervalDays: int('interval_days'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const alertRule = mysqlTable('alert_rule', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), category: varchar('category', { length: 100 }).notNull(), metric: varchar('metric', { length: 100 }).notNull(), warningPercent: decimal('warning_percent', { precision: 6, scale: 2 }).notNull(), criticalPercent: decimal('critical_percent', { precision: 6, scale: 2 }).notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const revenueRule = mysqlTable('revenue_rule', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), name: varchar('name', { length: 191 }).notNull(), billingType: varchar('billing_type', { length: 32 }).notNull(), origin: varchar('origin', { length: 191 }), destination: varchar('destination', { length: 191 }), rate: decimal('rate', { precision: 12, scale: 2 }).notNull(), validFrom: date('valid_from').notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const expenseCategory = mysqlTable('expense_category', { id: id(), ownerId: varchar('owner_id', { length: 191 }).notNull(), name: varchar('name', { length: 191 }).notNull(), scope: varchar('scope', { length: 32 }).notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const auditLog = mysqlTable('audit_log', { id: id(), userId: varchar('user_id', { length: 191 }).notNull(), action: varchar('action', { length: 64 }).notNull(), entity: varchar('entity', { length: 64 }).notNull(), entityId: varchar('entity_id', { length: 191 }), metadata: text('metadata'), createdAt: datetime('created_at').notNull().default(new Date()) })

export const trips = transportOperation
export const fuelRecords = fuelRecord
export const maintenanceRecords = maintenanceRecord
export const downtimeRecords = downtimeRecord
export const revenues = revenue
export const expenses = expense
export const monthlyClosures = monthlyClosure
export const incidents = incident
export const benchmarks = benchmark
export const notifications = notification
export const settings = setting
export const dailyOperations = transportOperation
export const auditLogs = auditLog
export const preventiveMaintenanceRules = preventiveMaintenanceRule
export const alertRules = alertRule
export const revenueRules = revenueRule
export const expenseCategories = expenseCategory
