import { boolean, date, datetime, decimal, index, int, mysqlTable, text, uniqueIndex, varchar } from 'drizzle-orm/mysql-core'

const id = () => int('id').autoincrement().primaryKey()
const owner = () => varchar('user_id', { length: 191 }).notNull()

export const user = mysqlTable('user', { id: varchar('id', { length: 191 }).primaryKey(), name: varchar('name', { length: 191 }).notNull(), email: varchar('email', { length: 191 }).notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), role: varchar('role', { length: 32 }).notNull().default('admin'), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()) })
export const session = mysqlTable('session', { id: varchar('id', { length: 191 }).primaryKey(), expiresAt: datetime('expiresAt').notNull(), token: varchar('token', { length: 191 }).notNull().unique(), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()), ipAddress: varchar('ipAddress', { length: 191 }), userAgent: text('userAgent'), userId: varchar('userId', { length: 191 }).notNull() })
export const account = mysqlTable('account', { id: varchar('id', { length: 191 }).primaryKey(), accountId: varchar('accountId', { length: 191 }).notNull(), providerId: varchar('providerId', { length: 191 }).notNull(), userId: varchar('userId', { length: 191 }).notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: datetime('accessTokenExpiresAt'), refreshTokenExpiresAt: datetime('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: datetime('createdAt').notNull().default(new Date()), updatedAt: datetime('updatedAt').notNull().default(new Date()) })
export const verification = mysqlTable('verification', { id: varchar('id', { length: 191 }).primaryKey(), identifier: varchar('identifier', { length: 191 }).notNull(), value: text('value').notNull(), expiresAt: datetime('expiresAt').notNull(), createdAt: datetime('createdAt').default(new Date()), updatedAt: datetime('updatedAt').default(new Date()) })

export const trucks = mysqlTable('trucks', { id: id(), userId: owner(), code: varchar('code', { length: 64 }).notNull(), plate: varchar('plate', { length: 16 }).notNull(), model: varchar('model', { length: 128 }).notNull(), brand: varchar('brand', { length: 128 }).notNull(), status: varchar('status', { length: 32 }).notNull().default('active'), currentDriver: varchar('current_driver', { length: 191 }), currentKm: decimal('current_km', { precision: 12, scale: 2 }).notNull().default('0'), benchmarkKmL: decimal('benchmark_km_l', { precision: 8, scale: 3 }).notNull().default('2.1'), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ ownerCode: uniqueIndex('trucks_owner_code').on(table.userId, table.code), ownerPlate: uniqueIndex('trucks_owner_plate').on(table.userId, table.plate) }))
export const dailyOperations = mysqlTable('daily_operations', { id: id(), userId: owner(), truckId: int('truck_id').notNull(), driverName: varchar('driver_name', { length: 191 }).notNull(), operationDate: date('operation_date').notNull(), km: decimal('km', { precision: 12, scale: 2 }).notNull(), trips: decimal('trips', { precision: 10, scale: 2 }).notNull(), tons: decimal('tons', { precision: 12, scale: 2 }).notNull(), liters: decimal('liters', { precision: 12, scale: 2 }).notNull(), kmPerTrip: decimal('km_per_trip', { precision: 12, scale: 4 }).notNull(), tonsPerTrip: decimal('tons_per_trip', { precision: 12, scale: 4 }).notNull(), kmPerLiter: decimal('km_per_liter', { precision: 12, scale: 4 }).notNull(), litersPer100Km: decimal('liters_per_100_km', { precision: 12, scale: 4 }).notNull(), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ userDate: index('daily_operations_user_date').on(table.userId, table.operationDate) }))
export const fuelRecords = mysqlTable('fuel_records', { id: id(), userId: owner(), truckId: int('truck_id').notNull(), driverName: varchar('driver_name', { length: 191 }).notNull(), recordDate: date('record_date').notNull(), km: decimal('km', { precision: 12, scale: 2 }).notNull(), liters: decimal('liters', { precision: 12, scale: 2 }).notNull(), pricePerLiter: decimal('price_per_liter', { precision: 12, scale: 4 }).notNull(), totalCost: decimal('total_cost', { precision: 14, scale: 2 }).notNull(), costPerKm: decimal('cost_per_km', { precision: 14, scale: 4 }).notNull(), station: varchar('station', { length: 191 }), fuelType: varchar('fuel_type', { length: 64 }), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ userDate: index('fuel_records_user_date').on(table.userId, table.recordDate) }))
export const drivers = mysqlTable('drivers', { id: id(), userId: owner(), name: varchar('name', { length: 191 }).notNull(), email: varchar('email', { length: 191 }), phone: varchar('phone', { length: 64 }), employeeId: varchar('employee_id', { length: 64 }), assignedTruckId: int('assigned_truck_id'), status: varchar('status', { length: 32 }).notNull().default('active'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const trips = mysqlTable('trips', { id: id(), userId: owner(), truckId: int('truck_id').notNull(), driverId: int('driver_id'), tripDate: date('trip_date').notNull(), origin: varchar('origin', { length: 191 }).notNull(), destination: varchar('destination', { length: 191 }).notNull(), km: decimal('km', { precision: 12, scale: 2 }).notNull(), tons: decimal('tons', { precision: 12, scale: 2 }).notNull(), startedAt: datetime('started_at'), notes: text('notes'), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ userDate: index('trips_user_date').on(table.userId, table.tripDate) }))
export const maintenanceRecords = mysqlTable('maintenance_records', { id: id(), userId: owner(), truckId: int('truck_id').notNull(), maintenanceDate: date('maintenance_date').notNull(), problem: varchar('problem', { length: 191 }).notNull(), description: text('description'), partsCost: decimal('parts_cost', { precision: 14, scale: 2 }).notNull().default('0'), laborCost: decimal('labor_cost', { precision: 14, scale: 2 }).notNull().default('0'), servicesCost: decimal('services_cost', { precision: 14, scale: 2 }).notNull().default('0'), totalCost: decimal('total_cost', { precision: 14, scale: 2 }).notNull().default('0'), workshop: varchar('workshop', { length: 191 }), status: varchar('status', { length: 32 }).notNull().default('open'), entryAt: datetime('entry_at'), exitAt: datetime('exit_at'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const downtimeRecords = mysqlTable('downtime_records', { id: id(), userId: owner(), truckId: int('truck_id').notNull(), reason: varchar('reason', { length: 191 }).notNull(), startedAt: datetime('started_at').notNull(), endedAt: datetime('ended_at'), description: text('description'), status: varchar('status', { length: 32 }).notNull().default('open'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const expenses = mysqlTable('expenses', { id: id(), userId: owner(), truckId: int('truck_id'), category: varchar('category', { length: 64 }).notNull(), amount: decimal('amount', { precision: 14, scale: 2 }).notNull(), expenseDate: date('expense_date').notNull(), description: text('description'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const revenues = mysqlTable('revenues', { id: id(), userId: owner(), truckId: int('truck_id'), tripId: int('trip_id'), origin: varchar('origin', { length: 191 }), destination: varchar('destination', { length: 191 }), tons: decimal('tons', { precision: 12, scale: 2 }).notNull().default('0'), trips: decimal('trips', { precision: 10, scale: 2 }).notNull().default('0'), km: decimal('km', { precision: 12, scale: 2 }).notNull().default('0'), amount: decimal('amount', { precision: 14, scale: 2 }).notNull(), revenueDate: date('revenue_date').notNull(), createdAt: datetime('created_at').notNull().default(new Date()) })
export const alerts = mysqlTable('alerts', { id: id(), userId: owner(), truckId: int('truck_id'), severity: varchar('severity', { length: 32 }).notNull(), title: varchar('title', { length: 191 }).notNull(), message: text('message').notNull(), resolvedAt: datetime('resolved_at'), createdAt: datetime('created_at').notNull().default(new Date()) })
export const auditLogs = mysqlTable('audit_logs', { id: id(), userId: owner(), entity: varchar('entity', { length: 64 }).notNull(), entityId: varchar('entity_id', { length: 191 }).notNull(), action: varchar('action', { length: 64 }).notNull(), oldValue: text('old_value'), newValue: text('new_value'), reason: text('reason'), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ entityIndex: index('audit_logs_entity').on(table.userId, table.entity, table.entityId) }))
export const monthlyClosures = mysqlTable('monthly_closures', { id: id(), userId: owner(), referenceMonth: date('reference_month').notNull(), status: varchar('status', { length: 32 }).notNull().default('open'), closedAt: datetime('closed_at'), closedBy: varchar('closed_by', { length: 191 }), createdAt: datetime('created_at').notNull().default(new Date()) }, table => ({ ownerMonth: uniqueIndex('monthly_closures_owner_month').on(table.userId, table.referenceMonth) }))
