'use client'

import { BarChart3, ClipboardList, FileSpreadsheet, LayoutDashboard, LogOut, Settings2, Truck, X } from 'lucide-react'
import { useState } from 'react'
import { authClient } from '@/lib/auth-client'

export default function ErpShell({ role, userName, children }: { role: 'admin' | 'accountant'; userName: string; children: React.ReactNode }) {
  const [menu, setMenu] = useState(false)
  const roleLabel = role === 'admin' ? 'Administrador' : 'Contador'
  return <main className="min-h-screen bg-background text-foreground"><aside className={`erp-sidebar ${menu ? 'erp-sidebar-open' : ''}`}><div className="flex items-center justify-between px-5 py-6"><a href="/" className="flex items-center gap-3"><div className="brand-mark"><Truck size={19} /></div><div><p className="brand-name">Cana<span>Log</span></p><p className="brand-caption">gestão empresarial</p></div></a><button className="icon-button erp-mobile-only" onClick={() => setMenu(false)} aria-label="Fechar menu"><X size={18} /></button></div><div className="erp-profile"><p className="eyebrow text-sidebar-foreground/50">Perfil ativo</p><p className="mt-2 text-sm font-medium">{roleLabel}</p><p className="mt-1 text-xs text-sidebar-foreground/50">{userName}</p></div><nav className="erp-nav"><p className="erp-nav-label">Visão geral</p><a href="/" onClick={() => setMenu(false)}><LayoutDashboard size={17} />Painel operacional</a><p className="erp-nav-label">Gestão</p><a href="#operacao" onClick={() => setMenu(false)}><ClipboardList size={17} />Operação e financeiro</a><a href="#analises" onClick={() => setMenu(false)}><BarChart3 size={17} />Análises avançadas</a><a href="#relatorios" onClick={() => setMenu(false)}><FileSpreadsheet size={17} />Relatórios e fechamento</a><p className="erp-nav-label">Sistema</p>  <a href="#configuracoes" onClick={() => setMenu(false)}><Settings2 size={17} />Configurações</a><a href="/account" onClick={() => setMenu(false)}><Settings2 size={17} />Segurança da conta</a></nav><div className="mt-auto px-3 pb-5"><button className="nav-item" onClick={() => authClient.signOut({ fetchOptions: { onSuccess: () => window.location.assign('/sign-in') } })}><LogOut size={18} /><span>Sair</span></button></div></aside><div className="erp-main"><header className="erp-topbar"><button className="icon-button erp-mobile-only" onClick={() => setMenu(true)} aria-label="Abrir menu"><span className="text-xl">☰</span></button><div><p className="eyebrow text-primary">CanaLog / área administrativa</p><h1 className="erp-page-title">Gestão completa</h1></div><div className="erp-topbar-actions"><span className="period-select">{roleLabel}</span><a className="secondary-button" href="/">Painel operacional</a></div></header><div className="erp-content">{children}</div></div></main>
}
