'use client'

import { useMemo, useState } from 'react'
import { BarChart3, CalendarDays, ChevronDown, CircleAlert, Fuel, LayoutDashboard, Menu, MoreHorizontal, Settings2, Truck, UsersRound, X, Zap, Wrench, FileText, Calculator, ShieldCheck, Plus, Search } from 'lucide-react'
import ThemeToggle from '@/components/theme-toggle'
import OperationForm from '@/components/operation-form'
import SpreadsheetImport from '@/components/spreadsheet-import'
import FuelForm from '@/components/fuel-form'
import EmployeeAccountForm from '@/components/employee-account-form'
import NotificationCenter from '@/components/notification-center'

type Trip = { id: number; date: string; tons: number; city: string; km: number; departure: string }
type FuelRecord = { date: string; liters: number; km: number; station: string; odometer: number }
type Props = { trips: Trip[]; fuel: FuelRecord[] }
type Module = 'Visão geral' | 'Operação diária' | 'Viagens e produção' | 'Abastecimentos' | 'Caminhões' | 'Motoristas' | 'Manutenção' | 'Relatórios e fechamento' | 'Configurações'

const nav: { label: Module; icon: typeof Truck }[] = [
  { label: 'Visão geral', icon: LayoutDashboard }, { label: 'Operação diária', icon: Zap }, { label: 'Viagens e produção', icon: BarChart3 }, { label: 'Abastecimentos', icon: Fuel }, { label: 'Caminhões', icon: Truck }, { label: 'Motoristas', icon: UsersRound }, { label: 'Manutenção', icon: Wrench }, { label: 'Relatórios e fechamento', icon: FileText }, { label: 'Configurações', icon: Settings2 },
]
const fmt = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 })
function dateFmt(value: string | Date | null | undefined) {
  if (!value) return '—'
  const raw = value instanceof Date ? value.toISOString() : value
  const normalized = /^\d{4}-\d{2}-\d{2}$/.test(raw) ? `${raw}T12:00:00` : raw
  const parsed = new Date(normalized)
  return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR').format(parsed)
}

function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Truck }) { return <article className="metric-card"><div className="metric-top"><span className="metric-icon"><Icon size={17} /></span><span className="metric-note">{note}</span></div><p className="metric-label">{label}</p><p className="metric-value">{value}</p></article> }
function SectionTitle({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) { return <div className="module-heading"><div><p className="eyebrow">CANALOG / OPERAÇÃO</p><h2>{title}</h2><p className="muted">{description}</p></div>{action && <button type="button" className="primary-action" onClick={onAction}><Plus size={16} /> {action}</button>}</div> }

export default function TransportDashboard({ trips, fuel }: Props) {
  const [active, setActive] = useState<Module>('Visão geral'); const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(''); const [showFuelForm, setShowFuelForm] = useState(false); const [showEmployeeForm, setShowEmployeeForm] = useState(false)
  const totals = useMemo(() => ({ tons: trips.reduce((s, x) => s + x.tons, 0), km: trips.reduce((s, x) => s + x.km, 0), liters: fuel.reduce((s, x) => s + x.liters, 0), journeys: trips.length }), [trips, fuel])
  const filteredTrips = trips.filter((x) => `${x.city} ${x.departure}`.toLowerCase().includes(query.toLowerCase()))
  const change = (label: Module) => { setActive(label); setMenuOpen(false) }
  const renderModule = () => {
    if (active === 'Visão geral') return <><div className="metrics-grid"><Metric label="Toneladas transportadas" value={`${fmt.format(totals.tons)} t`} note="Planilha importada" icon={BarChart3} /><Metric label="Viagens concluídas" value={fmt.format(totals.journeys)} note="Agosto 2026" icon={Truck} /><Metric label="Quilômetros rodados" value={`${fmt.format(totals.km)} km`} note="Todos os registros" icon={Zap} /><Metric label="Combustível registrado" value={`${fmt.format(totals.liters)} L`} note="Abastecimentos" icon={Fuel} /></div><SpreadsheetImport /><div className="content-grid"><section className="panel"><SectionTitle title="Últimas viagens" description="Operações carregadas da planilha de cana" action="Nova viagem" onAction={() => change('Operação diária')} /><div className="table-wrap"><table><thead><tr><th>Data</th><th>Destino</th><th>Saída</th><th>Toneladas</th><th>KM</th><th>Status</th></tr></thead><tbody>{filteredTrips.slice(-8).reverse().map((x) => <tr key={x.id}><td>{dateFmt(x.date)}</td><td>{x.city}</td><td>{x.departure || '—'}</td><td>{fmt.format(x.tons)} t</td><td>{fmt.format(x.km)}</td><td><span className="status-badge">Concluída</span></td></tr>)}</tbody></table></div></section><aside className="panel alert-panel"><SectionTitle title="Atenção operacional" description="Itens que pedem acompanhamento" /><div className="alert-item"><CircleAlert size={18} /><div><strong>Consumo sem referência</strong><p>2 abastecimentos não possuem KM informado.</p></div></div><div className="alert-item"><ShieldCheck size={18} /><div><strong>Dados importados</strong><p>{trips.length + fuel.length} registros disponíveis para conferência.</p></div></div></aside></div></>
    const descriptions: Record<Module, string> = { 'Operação diária': 'Registre a operação do motorista com validação imediata.', 'Viagens e produção': 'Consulte produção, destinos e desempenho por viagem.', 'Abastecimentos': 'Acompanhe litros, postos e eficiência da frota.', 'Caminhões': 'Visão da frota, disponibilidade e histórico operacional.', 'Motoristas': 'Motoristas vinculados e produtividade registrada.', 'Manutenção': 'Controle preventivo, corretivo e dias parados.', 'Relatórios e fechamento': 'Relatórios gerenciais e fechamento mensal da safra.', 'Configurações': 'Preferências, usuários e permissões do sistema.', 'Visão geral': '' }
    if (active === 'Operação diária') return <><SectionTitle title={active} description={descriptions[active]} /><OperationForm /></>
    const rows = active === 'Abastecimentos' ? fuel.map((x, i) => <tr key={i}><td>{dateFmt(x.date)}</td><td>{x.station || 'Posto não informado'}</td><td>{fmt.format(x.liters)} L</td><td>{fmt.format(x.km)} km</td><td>{fmt.format(x.odometer)}</td></tr>) : filteredTrips.map((x) => <tr key={x.id}><td>{dateFmt(x.date)}</td><td>{x.city}</td><td>{x.departure || '—'}</td><td>{fmt.format(x.tons)} t</td><td>{fmt.format(x.km)} km</td></tr>)
    const canAddOperation = active === 'Viagens e produção'
    const canAddFuel = active === 'Abastecimentos'
    const canAddEmployee = active === 'Motoristas'
    return <><SectionTitle title={active} description={descriptions[active]} action={canAddOperation ? 'Adicionar viagem' : canAddFuel ? 'Adicionar abastecimento' : canAddEmployee ? 'Cadastrar funcionário' : undefined} onAction={() => canAddOperation ? change('Operação diária') : canAddFuel ? setShowFuelForm(true) : setShowEmployeeForm(true)} />{showFuelForm && active === 'Abastecimentos' && <section className="panel mb-5"><SectionTitle title="Novo abastecimento" description="Informe os dados do combustível; o custo será calculado automaticamente." /><FuelForm onSaved={() => setShowFuelForm(false)} /></section>}{showEmployeeForm && active === 'Motoristas' && <section className="panel mb-5"><SectionTitle title="Novo funcionário" description="O administrador cria o acesso inicial de motoristas e contadores." /><EmployeeAccountForm onSaved={() => setShowEmployeeForm(false)} /></section>}<div className="toolbar"><div className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar nos registros..." /></div><button className="filter-button"><CalendarDays size={15} /> Agosto 2026 <ChevronDown size={14} /></button></div><section className="panel"><div className="table-wrap"><table><thead><tr>{active === 'Abastecimentos' ? <><th>Data</th><th>Posto</th><th>Litros</th><th>KM</th><th>Odômetro</th></> : <><th>Data</th><th>Destino</th><th>Saída</th><th>Produção</th><th>Distância</th></>}</tr></thead><tbody>{rows}</tbody></table></div></section></>
  }
  return <div className="app-frame"><aside className={`app-sidebar ${menuOpen ? 'is-open' : ''}`}><div className="sidebar-brand"><div className="brand-symbol"><span /></div><div><strong>Cana<span>Log</span></strong><small>gestão operacional</small></div><button className="mobile-close" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X size={18} /></button></div><div className="season-card"><span className="status-dot" /><div><small>SAFRA ATIVA</small><strong>Agosto · 2026</strong></div><ChevronDown size={15} /></div><nav className="sidebar-nav"><p>MENU PRINCIPAL</p>{nav.slice(0, 6).map(({ label, icon: Icon }) => <button key={label} className={active === label ? 'active' : ''} onClick={() => change(label)}><Icon size={18} /><span>{label}</span>{label === 'Abastecimentos' && <b>2</b>}</button>)}<p className="nav-spacer">GESTÃO</p>{nav.slice(6).map(({ label, icon: Icon }) => <button key={label} className={active === label ? 'active' : ''} onClick={() => change(label)}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="sidebar-user"><div className="user-avatar">GC</div><div><strong>Guilherme Costa</strong><small>Administrador</small></div><MoreHorizontal size={18} /></div></aside><section className="app-content"><header className="topbar"><button className="mobile-menu" onClick={() => setMenuOpen(true)} aria-label="Abrir menu"><Menu size={20} /></button><div><p className="breadcrumb">CanaLog <span>/</span> {active}</p><h1>{active}</h1></div><div className="top-actions"><button className="period-button"><CalendarDays size={16} /> 01 — 31 Ago 2026 <ChevronDown size={14} /></button><NotificationCenter /><ThemeToggle /><div className="top-avatar">GC</div></div></header><main className="dashboard-main">{renderModule()}</main></section></div>
}
